openapi: 3.0.0
info:
  title: githubreader
  version: '1.0'
servers:
  - url: 'http://localhost:3000'
paths:
  /readrepo:
    post:
      summary: Read repo
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ReadRepoResponse'
        '404':
          description: Not Found
        '422':
          description: Unprocessable Entity (WebDAV)
      operationId: readrepo
      description: 'Scrapes a github repo, returning the number of lines and size of all files grouped by file extension.'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ReadRepoRequest'
    parameters: []
components:
  schemas:
    ReadRepoResponse:
      title: ReadRepoResponse
      type: object
      description: ''
      properties:
        totalLines:
          type: number
        totalSize:
          type: string
        fileCount:
          type: number
        fileGroups:
          type: array
          items:
            $ref: '#/components/schemas/ReadRepoGroup'
      required:
        - totalLines
        - totalSize
        - fileCount
        - fileGroups
    ReadRepoGroup:
      title: ReadRepoGroup
      type: object
      properties:
        fileExtension:
          type: string
        lineCount:
          type: number
        totalSize:
          type: string
        files:
          type: array
          items:
            $ref: '#/components/schemas/ReadRepoFile'
      required:
        - fileExtension
        - lineCount
        - totalSize
        - files
    ReadRepoFile:
      title: ReadRepoFile
      type: object
      properties:
        name:
          type: string
        lineCount:
          type: number
        size:
          type: string
      required:
        - name
        - lineCount
        - size
    ReadRepoRequest:
      title: ReadRepoRequest
      type: object
      properties:
        url:
          type: string
      required:
        - url
