/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (4.3.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.thiago.githubreader.adapters.web.api;

import com.thiago.githubreader.adapters.web.model.ReadRepoResponseApiModel;
import io.swagger.annotations.*;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.CookieValue;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.context.request.NativeWebRequest;
import org.springframework.web.multipart.MultipartFile;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
import java.util.Map;
import java.util.Optional;

@Validated
@Api(value = "readrepo", description = "the readrepo API")
public interface ReadrepoApi {

    /**
     * GET /readrepo/{repoURL} : Your GET endpoint
     * Scrapes a github repo, returning the number of lines and size of all files grouped by file extension.
     *
     * @param repoURL  (required)
     * @return OK (status code 200)
     *         or Not Found (status code 404)
     */
    @ApiOperation(value = "Your GET endpoint", nickname = "readrepo", notes = "Scrapes a github repo, returning the number of lines and size of all files grouped by file extension.", response = ReadRepoResponseApiModel.class, tags={  })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "OK", response = ReadRepoResponseApiModel.class),
        @ApiResponse(code = 404, message = "Not Found") })
    @RequestMapping(value = "/readrepo/{repoURL}",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    ResponseEntity<ReadRepoResponseApiModel> readrepo(@ApiParam(value = "",required=true) @PathVariable("repoURL") String repoURL);

}
